from pathlib import Path
p=Path('index.html')
s=p.read_text()
marker='MOLMS-FINANCE-CARRYFORWARD-RECEIVABLES-V1'
if marker in s:
    print('already patched'); raise SystemExit
patch=r'''
<script>
/* MOLMS-FINANCE-CARRYFORWARD-RECEIVABLES-V1 */
(function(){
 function money(n){return Number(n||0).toLocaleString();}
 function approved(t){return (t.status||'')==='approved'||t.is_approved===true;}
 function ensureFields(){const amt=document.getElementById('fdManualAmount');if(!amt||document.getElementById('fdClientReceivableWrap'))return;const w=document.createElement('div');w.id='fdClientReceivableWrap';w.style='margin-top:10px;border:1px solid var(--border);border-radius:10px;padding:10px;background:#fafafa';w.innerHTML=`<label style="display:flex;gap:8px;align-items:center;font-size:12px;font-weight:700"><input id="fdClientReceivable" type="checkbox" onchange="fdToggleClientReceivable()"> This is a payment against an amount owed by a client</label><div id="fdClientReceivableFields" style="display:none;margin-top:10px;grid-template-columns:1fr 1fr;gap:8px"><input id="fdReceivableClient" class="search" placeholder="Client name"><input id="fdReceivableMatter" class="search" placeholder="Matter / reference (optional)"><input id="fdAgreedAmount" type="number" min="0" step="0.01" class="search" placeholder="Agreed amount"><div id="fdOutstandingPreview" style="padding:8px;font-size:12px;font-weight:700;color:var(--navy)">Outstanding: —</div></div>`;amt.closest('div[style*="grid-template-columns"]')?.after(w);amt.addEventListener('input',fdUpdateOutstandingPreview);}
 window.fdToggleClientReceivable=function(){const on=document.getElementById('fdClientReceivable')?.checked,f=document.getElementById('fdClientReceivableFields');if(f)f.style.display=on?'grid':'none';fdUpdateOutstandingPreview();};
 window.fdUpdateOutstandingPreview=function(){const a=Number(document.getElementById('fdAgreedAmount')?.value||0),r=Number(document.getElementById('fdManualAmount')?.value||0),e=document.getElementById('fdOutstandingPreview');if(e)e.textContent=a>0?'Outstanding: '+money(Math.max(0,a-r)):'Outstanding: —';};
 const oo=window.fdOpenManualModal;if(oo)window.fdOpenManualModal=function(){const r=oo.apply(this,arguments);setTimeout(()=>{ensureFields();const c=document.getElementById('fdClientReceivable');if(c)c.checked=false;fdToggleClientReceivable();},0);return r;};
 const oe=window.fdEditManual;if(oe)window.fdEditManual=async function(id){await oe.apply(this,arguments);ensureFields();const t=(_fdAllManual||[]).find(x=>x.id===id);if(t){document.getElementById('fdClientReceivable').checked=!!t.client_receivable;document.getElementById('fdReceivableClient').value=t.receivable_client_name||t.counterparty||'';document.getElementById('fdReceivableMatter').value=t.receivable_matter_ref||'';document.getElementById('fdAgreedAmount').value=t.agreed_amount||'';fdToggleClientReceivable();}};
 const os=window.fdSaveManual;if(os)window.fdSaveManual=async function(){const on=!!document.getElementById('fdClientReceivable')?.checked;if(!on)return os.apply(this,arguments);const amount=Number(document.getElementById('fdManualAmount')?.value||0),agreed=Number(document.getElementById('fdAgreedAmount')?.value||0),client=(document.getElementById('fdReceivableClient')?.value||document.getElementById('fdManualCounterparty')?.value||'').trim();if(!client||agreed<=0||amount<=0||amount>agreed){notice('For a client receivable, enter the client, agreed amount and amount received. Amount received cannot exceed the agreed amount.','err');return;}const editId=document.getElementById('fdManualId')?.value||null;await os.apply(this,arguments);let q=editId?sb.from('fd_manual_transactions').select('id').eq('id',editId):sb.from('fd_manual_transactions').select('id').eq('client_receivable',false).eq('amount',amount).order('created_at',{ascending:false}).limit(1);const {data}=await q.maybeSingle();if(data?.id){await sb.from('fd_manual_transactions').update({client_receivable:true,agreed_amount:agreed,outstanding_amount:Math.max(0,agreed-amount),receivable_client_name:client,receivable_matter_ref:(document.getElementById('fdReceivableMatter')?.value||'').trim()||null}).eq('id',data.id);await fdRefresh();}};
 window.fdCarryForwardSnapshot=function(){const d=new Date((_fdPeriodStart||new Date()).toString()),start=d.toISOString().slice(0,10),pm=(_fdAllManual||[]).filter(t=>t.date<start&&approved(t)),cin=pm.filter(t=>['revenue','loan'].includes(t.tx_type)).reduce((s,t)=>s+Number(t.amount||0),0)+(_fdAllInvoices||[]).flatMap(fdInvoiceCashReceipts).filter(r=>r.date<start).reduce((s,r)=>s+Number(r.amount||0),0),cout=pm.filter(t=>['expenditure','drawing'].includes(t.tx_type)).reduce((s,t)=>s+Number(t.amount||0),0);return {openingCash:cin-cout};};
 window.fdRenderReceivablesCard=function(){let h=document.getElementById('fdReceivablesCardV1');if(!h){h=document.createElement('div');h.id='fdReceivablesCardV1';h.className='card';h.style='margin-top:12px;padding:14px';}const rows={};(_fdAllInvoices||[]).filter(i=>i.invoice_type==='tax'&&!['void','cancelled','draft','paid'].includes(i.status)).forEach(i=>{const b=Math.max(0,Number(i.total_due||0)-Number(i.amount_paid||0)-Number(i.withholding_tax_amount||0));if(b>0){const k=i.client_name||'Unnamed client';rows[k]=(rows[k]||0)+b;}});(_fdAllManual||[]).filter(t=>approved(t)&&t.client_receivable&&Number(t.outstanding_amount||0)>0).forEach(t=>{const k=t.receivable_client_name||t.counterparty||'Unnamed client';rows[k]=(rows[k]||0)+Number(t.outstanding_amount||0);});const list=Object.entries(rows).sort((a,b)=>b[1]-a[1]),total=list.reduce((s,x)=>s+x[1],0);h.innerHTML=`<div style="display:flex;justify-content:space-between"><div><div style="font-size:11px;color:var(--muted);font-weight:800;text-transform:uppercase">Receivables</div><div style="font-size:22px;font-weight:800;color:var(--navy)">TZS ${money(total)}</div></div><div style="font-size:11px;color:var(--muted)">Who owes the firm</div></div><div style="margin-top:8px">${list.slice(0,5).map(([n,v])=>`<div style="display:flex;justify-content:space-between;padding:5px 0;border-top:1px solid var(--border);font-size:12px"><span>${esc(n)}</span><strong>TZS ${money(v)}</strong></div>`).join('')||'<div style="font-size:12px;color:var(--muted);padding-top:8px">No open receivables.</div>'}</div>`;const target=document.getElementById('fdDashboard')||document.querySelector('#findash');if(target&&!h.parentNode)target.appendChild(h);};
 const or=window.fdRender;if(or)window.fdRender=async function(){const r=await or.apply(this,arguments);try{fdRenderReceivablesCard();}catch(e){console.warn(e)}return r;};document.addEventListener('DOMContentLoaded',ensureFields);
})();
</script>
'''
pos=s.lower().rfind('</body>')
if pos<0:raise SystemExit('no body')
p.write_text(s[:pos]+patch+s[pos:])
print('patched v1')
